image: python:3.8

stages:
    - staging
    - production

staging:
    type: deploy
    stage: staging
    variables:
        HEROKU_APP: enogrid-staging
        HEROKU_API_KEY: b064e520-936c-4c5b-88af-cfa53d64735a
    script:
        - git remote add heroku https://git.heroku.com/enogrid-staging.git
        - git push heroku HEAD:refs/heads/staging
    only:
        - staging

production:
    type: deploy
    stage: production
    variables:
        HEROKU_APP: enogrid
        HEROKU_API_KEY: b064e520-936c-4c5b-88af-cfa53d64735a
    script:
        - git remote add heroku https://git.heroku.com/enogrid.git
        - git push heroku HEAD:refs/heads/master
    only:
        - master