image: python:3.8

before_script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt

stages:
    - staging
    - production

staging:
    type: deploy
    stage: staging
    script:
	# this configures Django application to use attached postgres database that is run on `postgres` host
	- export DATABASE_URL=postgres://postgres:@postgres:5432/python-test-app
        - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
    only:
        - staging

production:
    type: deploy
    stage: production
    script:
        - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
    only:
        - master
