version: "3"

services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: "enogrid"
      POSTGRES_PASSWORD: "acdc"
      POSTGRES_DB: "enogrid_acdc"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  pgadmin:
    image: "dpage/pgadmin4:latest"
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
#   volumes:
#     - "./data/pgadmin:/var/lib/pgadmin"
    ports:
      - "8080:80"